clc
clear

if isunix
    lib = '/usr/local/lib/libbloch_sim.so';
    src = fullfile(fileparts(mfilename('fullpath')), 'bloch_mex.cpp');   
    out_path = fileparts(mfilename('fullpath'));
    mex('-v', lib, src, '-R2018a', '-outdir', out_path);

elseif ispc
    mex -I'C:\Program Files (x86)\Intel\oneAPI\mkl\latest\include' ...
    -L'C:\Program Files (x86)\Intel\oneAPI\mkl\latest\lib\intel64' ...
    -L'C:\Program Files (x86)\Intel\oneAPI\compiler\latest\windows\compiler\lib\intel64_win' ...
    -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -llibiomp5md ...
    -I'./oneapi-tbb/include' ...
    -L'./oneapi-tbb/lib/intel64/vc14' ...
    -ltbb -D_TBB ...    
    MATLAB_example/bloch_mex.cpp bloch.cpp -R2018a
    
else
    error('Platform not supported')
end
